//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTDAPI.Ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskList
    {
        public int id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public Nullable<int> taskType { get; set; }
        public Nullable<int> parentId { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> taskDate { get; set; }
        public System.DateTime createdon { get; set; }
    
        public virtual TaskType TaskType1 { get; set; }
        public virtual User User { get; set; }
    }
}
